/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package projekakhirperpustakaan;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Ridho
 */
public class panelDashbord extends javax.swing.JPanel {

    /**
     * Creates new form panelDashbord
     */
    public panelDashbord() {
        initComponents();
        load_user();
        load_buku();
        load_pinjaman();
        load_rank();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbRank = new javax.swing.JTable();
        panelRound1 = new test.PanelRound();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        countBuku = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelRound2 = new test.PanelRound();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        countUser = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        panelRound3 = new test.PanelRound();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        countLoan = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        panelRound4 = new test.PanelRound();
        totalTop = new javax.swing.JLabel();
        judulTopPinjam = new javax.swing.JLabel();
        penulisTop = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        imageTopPinjam = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(764, 519));
        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(137, 168, 178));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        tbRank.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        tbRank.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No", "Judul Buku", "Kuantitas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbRank.setToolTipText("berdasarkan banyak peminjaman");
        tbRank.setRowHeight(30);
        tbRank.setRowMargin(5);
        jScrollPane2.setViewportView(tbRank);
        if (tbRank.getColumnModel().getColumnCount() > 0) {
            tbRank.getColumnModel().getColumn(0).setResizable(false);
            tbRank.getColumnModel().getColumn(0).setPreferredWidth(10);
            tbRank.getColumnModel().getColumn(1).setPreferredWidth(150);
        }

        jPanel2.add(jScrollPane2);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 300, 300));

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottomLeft(60);
        panelRound1.setRoundBottomRight(60);
        panelRound1.setRoundTopLeft(60);
        panelRound1.setRoundTopRight(60);

        jLabel5.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Jumlah Buku");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/book (1).png"))); // NOI18N

        countBuku.setFont(new java.awt.Font("Poppins SemiBold", 0, 48)); // NOI18N
        countBuku.setText("99");

        jLabel4.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Dengan Judul berbeda");

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(countBuku)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(countBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 200, 150));

        panelRound2.setBackground(new java.awt.Color(255, 255, 255));
        panelRound2.setRoundBottomLeft(60);
        panelRound2.setRoundBottomRight(60);
        panelRound2.setRoundTopLeft(60);
        panelRound2.setRoundTopRight(60);

        jLabel15.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Jumlah User");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/user.png"))); // NOI18N

        countUser.setFont(new java.awt.Font("Poppins SemiBold", 0, 48)); // NOI18N
        countUser.setText("99");

        jLabel17.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("User Terdaftar");

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(countUser)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(countUser, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRound2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 210, 150));

        panelRound3.setBackground(new java.awt.Color(255, 255, 255));
        panelRound3.setRoundBottomLeft(60);
        panelRound3.setRoundBottomRight(60);
        panelRound3.setRoundTopLeft(60);
        panelRound3.setRoundTopRight(60);

        jLabel18.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("On Loan");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/scholarship.png"))); // NOI18N

        countLoan.setFont(new java.awt.Font("Poppins SemiBold", 0, 48)); // NOI18N
        countLoan.setText("99");

        jLabel20.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Buku Dipinjam");

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(countLoan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(countLoan, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(panelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, 200, 150));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/promotional.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, -1, -1));

        panelRound4.setBackground(new java.awt.Color(255, 255, 255));
        panelRound4.setRoundBottomLeft(60);
        panelRound4.setRoundBottomRight(60);
        panelRound4.setRoundTopLeft(60);
        panelRound4.setRoundTopRight(60);
        panelRound4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        totalTop.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        totalTop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalTop.setText("Total Pinjaman : xx");
        panelRound4.add(totalTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 360, -1));

        judulTopPinjam.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        judulTopPinjam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelRound4.add(judulTopPinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 360, -1));

        penulisTop.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        penulisTop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        penulisTop.setText("Oleh : xxx");
        panelRound4.add(penulisTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 360, -1));

        jPanel4.setPreferredSize(new java.awt.Dimension(133, 168));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));
        jPanel4.add(imageTopPinjam);

        panelRound4.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/quality.png"))); // NOI18N
        panelRound4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jPanel1.add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 360, 300));

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel countBuku;
    private javax.swing.JLabel countLoan;
    public javax.swing.JLabel countUser;
    private javax.swing.JLabel imageTopPinjam;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel judulTopPinjam;
    private test.PanelRound panelRound1;
    private test.PanelRound panelRound2;
    private test.PanelRound panelRound3;
    private test.PanelRound panelRound4;
    private javax.swing.JLabel penulisTop;
    private javax.swing.JTable tbRank;
    private javax.swing.JLabel totalTop;
    // End of variables declaration//GEN-END:variables

    private void load_user() {
        String query = "SELECT COUNT(*) AS total_user FROM user";
        try (Connection conn = Koneksi.getKoneksi();
             PreparedStatement stmt = conn.prepareStatement(query);
             ResultSet res = stmt.executeQuery()) {

            if (res.next()) {
                int totalUser = res.getInt("total_user");
                countUser.setText(""+totalUser);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void load_buku() {
        String query = "SELECT COUNT(*) AS total_buku FROM buku";
        try (Connection conn = Koneksi.getKoneksi();
             PreparedStatement stmt = conn.prepareStatement(query);
             ResultSet res = stmt.executeQuery()) {

            if (res.next()) {
                int totalBuku = res.getInt("total_buku");
                countBuku.setText(""+totalBuku);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void load_pinjaman() {
        String query = "SELECT COUNT(*) AS total_bukuPinjam FROM tranksaksi where status = 'dipinjam'";
        try (Connection conn = Koneksi.getKoneksi();
             PreparedStatement stmt = conn.prepareStatement(query);
             ResultSet res = stmt.executeQuery()) {

            if (res.next()) {
                int totalBukuPinjam = res.getInt("total_bukuPinjam");
                countLoan.setText(""+totalBukuPinjam);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void load_rank() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("Judul Buku");
        model.addColumn("Jumlah");
        try {
            int no = 1;
            String sql = "SELECT b.judul_buku, COUNT(a.book_id) AS jumlah_dipinjam, "
                    + " b.id_buku , b.pengarang, b.path_gambar FROM tranksaksi a JOIN buku b ON a.book_id = b.id_buku WHERE a.status = 'dipinjam' "
                    + "GROUP BY a.book_id ORDER BY jumlah_dipinjam DESC LIMIT 10" ;
            Connection conn = Koneksi.getKoneksi();
            java.sql.Statement  stm= conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            String judulBukuTop = "";
            String penulisBukuTop = "";
            String pathGambarBukuTop = "";
            String countPinjaman = "";
            while (res.next()){
                model.addRow(
                        new Object[]{
                            no++,
                            res.getString("judul_buku"),
                            res.getString("jumlah_dipinjam")
                        }
                );
                if (no == 2) {
                judulBukuTop = res.getString("judul_buku");
                penulisBukuTop = res.getString("pengarang");
                countPinjaman = res.getString("jumlah_dipinjam");
                pathGambarBukuTop = res.getString("path_gambar");
            }
            }
            tbRank.setModel(model);
            tbRank.getColumnModel().getColumn(1).setPreferredWidth(300);
            judulTopPinjam.setText(judulBukuTop);
            penulisTop.setText("Penulis : "+penulisBukuTop);
            totalTop.setText("Dipinjam : "+countPinjaman +" Kali");
            if (pathGambarBukuTop != null && !pathGambarBukuTop.isEmpty()) {
                ImageIcon icon = new ImageIcon(pathGambarBukuTop);
                imageTopPinjam.setIcon(icon);
                imageTopPinjam.setText("");
            }      
            
            
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat mengambil data.");
        }
    }
    
 }

