/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projekakhirperpustakaan;

/**
 *
 * @author Ridho
 */
public class splashFrame extends javax.swing.JFrame {

    /**
     * Creates new form splashFrame
     */
    public splashFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        txt1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt2 = new javax.swing.JLabel();
        txt3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(219, 226, 239));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jProgressBar1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 600, 960, 20));

        txt1.setFont(new java.awt.Font("Poppins", 1, 48)); // NOI18N
        txt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt1.setText("LOADING ....");
        jPanel1.add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 910, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/a7a129a23365d95672dca803de1f1b83_423169860289023215.gif"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 131, -1));

        txt2.setFont(new java.awt.Font("Poppins Medium", 0, 10)); // NOI18N
        txt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt2.setText("Memuat Data ...");
        jPanel1.add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 570, 730, -1));

        txt3.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        txt3.setText("0 %");
        jPanel1.add(txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 570, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-14, -4, 930, 620));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
  
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(splashFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(splashFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(splashFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(splashFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
    splashFrame sp = new splashFrame();
    sp.setVisible(true);
    frameLogin fl = new frameLogin();
    fl.setVisible(false);
    
        try {
            for(int i=0;i<=100;i++){
                Thread.sleep(70);
                sp.txt3.setText(i+" %");
                sp.jProgressBar1.setValue(i);
                if (i == 10){
                    sp.txt1.setText("Masih Menunggu");
                    sp.txt2.setText("Yang sabar yahhh");
                }
                if (i == 20){
                    sp.txt1.setText("Sabar Masih 20%");
                    sp.txt2.setText("Ayam, ayam apa yang besar ? AYAM SEMESTA");
                }if (i == 40){
                    sp.txt1.setText("Capek ? Sabar dikit");
                    sp.txt2.setText("Kuliah , Beli Geprek mawar , Pulang");
                }if (i == 70){
                    sp.txt1.setText("Hampir selesai");
                    sp.txt2.setText("Kamu hebat sudah menunggu sampai saat ini");
                }
                if (i == 90){
                    sp.txt1.setText("Proses Login");
                    sp.txt2.setText("cihuyyy kamu udah mau login nih");
                }
                if( i == 100){
                    sp.dispose();
                    fl.setVisible(true);
                }
            }
        } catch (Exception e) {
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel txt1;
    private javax.swing.JLabel txt2;
    private javax.swing.JLabel txt3;
    // End of variables declaration//GEN-END:variables
}
